name: robanokyuka
description: "ロバの休暇"
publish_to: "none"
version: 0.4.0+1
environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.5.0
  flutter_native_splash: ^2.4.7
  firebase_auth: ^6.2.0
  cloud_functions: ^6.0.7
  cloud_firestore: ^6.1.3
  fpdart: ^1.2.0
  shared_preferences: ^2.5.4
  hooks_riverpod: ^3.3.1
  flutter_hooks: ^0.21.3+1
  url_launcher: ^6.3.2
  flutter_markdown_plus: ^1.0.7
  markdown: ^7.3.1
  web: ^1.1.1
  material_symbols_icons: ^4.2928.1
  path: ^1.9.1
  flutter_svg: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_auth_mocks: ^0.15.1
  fake_cloud_firestore: ^4.1.0+1
  mock_exceptions: ^0.8.2
flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
  assets:
    - assets/
