import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found. Run from the project root.');
    exitCode = 1;
    return;
  }

  final versionLine = pubspec
      .readAsLinesSync()
      .where((line) => line.startsWith('version:'))
      .firstOrNull;

  if (versionLine == null) {
    stderr.writeln('Error: version field not found in pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final version = versionLine.replaceFirst('version:', '').trim();
  final semver = version.split('+').first;

  final output = File('lib/config/version.dart');
  output.writeAsStringSync(
    "// Generated by tools/set_ui_version.dart — do not edit manually.\n"
    "const packageVersion = '$version';\n",
  );
  stdout.writeln('Set packageVersion to "$version" in lib/config/version.dart');

  final packageJson = File('package.json');
  if (!packageJson.existsSync()) {
    stderr.writeln('Error: package.json not found.');
    exitCode = 1;
    return;
  }

  final updatedPackageJson = packageJson.readAsStringSync().replaceFirstMapped(
    RegExp(r'"version"\s*:\s*"[^"]*"'),
    (_) => '"version": "$semver"',
  );
  packageJson.writeAsStringSync(updatedPackageJson);
  stdout.writeln('Set version to "$semver" in package.json');

  final envFile = File('functions/.env.local');
  final envLines = ['NODE_ENV=development', 'APP_VERSION_URL=$version'];
  envFile.writeAsStringSync('${envLines.join('\n')}\n');
  stdout.writeln('Set APP_VERSION_URL to "$version" in functions/.env.local');

  final googleServerClientIdFile = File(
    'lib/config/google_server_client_id.dart',
  );
  googleServerClientIdFile.writeAsStringSync(
    "// Generated by tools/set_google_server_client_id.dart — do not edit manually.\n"
    "const String googleServerClientId = 'GOOGLE_SERVER_CLIENT_ID';\n",
  );
  stdout.writeln(
    'Reset googleServerClientId to placeholder in '
    'lib/config/google_server_client_id.dart',
  );
}
