import 'dart:convert';
import 'dart:io';

void main() {
  final jsonFile = File('android/app/google-services.json');
  if (!jsonFile.existsSync()) {
    stderr.writeln(
      'Error: android/app/google-services.json not found. '
      'Run from the project root.',
    );
    exit(1);
  }

  late Map<String, dynamic> json;
  try {
    json = jsonDecode(jsonFile.readAsStringSync()) as Map<String, dynamic>;
  } catch (e) {
    stderr.writeln(
      'Error: Failed to parse android/app/google-services.json: $e',
    );
    exit(1);
  }

  String? clientId;
  try {
    final clients = json['client'] as List<dynamic>;
    for (final client in clients) {
      final oauthClients =
          (client as Map<String, dynamic>)['oauth_client'] as List<dynamic>;
      for (final oauth in oauthClients) {
        final entry = oauth as Map<String, dynamic>;
        if (entry['client_type'] == 3) {
          clientId = entry['client_id'] as String;
          break;
        }
      }
      if (clientId != null) break;
    }
  } catch (e) {
    stderr.writeln(
      'Error: Unexpected structure in android/app/google-services.json: $e',
    );
    exit(1);
  }

  if (clientId == null) {
    stderr.writeln(
      'Error: No oauth_client with client_type 3 found in '
      'android/app/google-services.json.',
    );
    exit(1);
  }

  final outputFile = File('lib/config/google_server_client_id.dart');
  try {
    outputFile.writeAsStringSync(
      '// Generated by tools/set_google_server_client_id.dart'
      ' — do not edit manually.\n'
      "const String googleServerClientId = '$clientId';\n",
    );
  } catch (e) {
    stderr.writeln(
      'Error: Failed to write lib/config/google_server_client_id.dart: $e',
    );
    exit(1);
  }

  stdout.writeln(
    'Set googleServerClientId to "$clientId" in '
    'lib/config/google_server_client_id.dart',
  );
}
