name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/firebase-hosting-merge.yml
      - assets/**/*
      - docs/**/*
      - lib/**/*
      - web/**/*
      - pubspec.*
      - firebase.json
      - codecov.yml
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Test Flutter
        run: flutter test --coverage
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Filter Flutter coverage
        run: lcov --extract coverage/lcov.info 'lib/models/*' 'lib/services/*' --output-file coverage/lcov.info
      - name: Upload Flutter coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: flutter
      - name: Set firebase api key
        run: |
          sed 's/FIREBASE_API_KEY/${{ secrets.FIREBASE_API_KEY_ROBANOKYUKA }}/' \
            -i lib/config/firebase.dart
      - name: Build web
        run: dart tools/md2html.dart && dart tools/set_ui_version.dart && flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROBANOKYUKA }}
          channelId: live
          projectId: robanokyuka
      - name: Update data
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROBANOKYUKA }}' \
          > $GOOGLE_APPLICATION_CREDENTIALS
          npx firebase firestore:delete -f service/version
