name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/firebase-android-merge.yml
      - .github/workflows/firebase-firestore-merge.yml
      - .github/workflows/firebase-functions-merge.yml
      - .github/workflows/firebase-hosting-pull-request.yml
      - .github/workflows/firebase-storage-merge.yml
      - .vscode/**/*
      - functions/**/*
      - android/**/*
      - ios/**/*
      - test/**/*
      - firestore.*
      - storage.*
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: dart tools/set_ui_version.dart
      - name: Set firebase config
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_ROBANOKYUKA }}
        run: echo "$FIREBASE_CONFIG" > lib/config/firebase_config.dart
      - run: flutter test --coverage
      - name: Filter Flutter coverage
        run: |
          sudo apt-get install -y lcov && \
          lcov --extract coverage/lcov.info 'lib/models/*' 'lib/services/*' --output-file coverage/lcov.info
      - name: Upload Flutter coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: flutter

      - run: flutter build web --web-renderer canvaskit --no-tree-shake-icons
      - run: dart tools/md2html.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROBANOKYUKA }}
          channelId: live
          projectId: robanokyuka

      - name: Update data
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/service-account.json
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROBANOKYUKA }}' \
          > $GOOGLE_APPLICATION_CREDENTIALS
          npx firebase firestore:delete -f service/version
